import = ["~/.config/alacritty/catppuccin-mocha.toml"]
[env]
TERM = "xterm-256color"
[window]
opacity = 0.8
decorations = "none"

[window.padding]
x = 7
y = 0

[font.normal]
family = "FiraCode Nerd Font"
