general {
    hide_cursor = true
    immediate_render = true
}

background {
    monitor =
    path = ~/dotfiles/macos-theme/wallpapers/nyx-umbra-guardian-16x9.png
    color = rgba(0d0b14ff)
    blur_passes = 1
    blur_size = 3
    noise = 0.012
    contrast = 0.92
    brightness = 0.72
}

label {
    monitor =
    text = $TIME
    color = rgba(dad6ebff)
    font_family = JetBrainsMono Nerd Font
    font_size = 68
    position = 0, 110
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date '+%A, %B %d'
    color = rgba(aaa3bfff)
    font_family = Inter
    font_size = 16
    position = 0, 45
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 320, 52
    outline_thickness = 2
    dots_size = 0.24
    dots_spacing = 0.32
    outer_color = rgba(b69cffff)
    inner_color = rgba(171522e6)
    font_color = rgba(dad6ebff)
    check_color = rgba(82aaffff)
    fail_color = rgba(f2778fff)
    capslock_color = rgba(e7bd78ff)
    placeholder_text = <span foreground="##81799c">Password</span>
    fail_text = <span foreground="##f2778f">Authentication failed</span>
    rounding = 10
    position = 0, -55
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER  ·  umbra
    color = rgba(81799cff)
    font_family = JetBrainsMono Nerd Font
    font_size = 13
    position = 0, -112
    halign = center
    valign = center
}
